import {ImageInterface} from "./image.interface";
import {SkinInterface} from "./skin.interface";
import {TagEnum} from "../enum/tag.enum";
import {InfoInterface} from "./info.interface";
import {StatInterface} from "./stat.interface";
import {SpellInterface} from "./spell.interface";
import {PassiveInterface} from "./passive.interface";

export interface ChampionInterface {

    uuid?: string; //uuid generated by afklol
    id?: string; // id on riot api (ex : "Aatrox")
    key?: string; // id on riot api (ex : "266")
    name?: string;
    title?: string;
    free?: boolean;
    pricePI?: number;
    priceRP?: number;
    image?: ImageInterface;
    skins?: SkinInterface[];
    lore?: string;
    blurb?: string;
    allytips?: string[];
    enemytips?: string[];
    tags?: TagEnum[];
    partype?: string
    info?: InfoInterface;
    stats?: StatInterface;
    spells?: SpellInterface[];
    passive?: PassiveInterface;
    recommended: any[];
}
