export interface ImageInterface {
    uuid?: string; //uuid generated by afklol
    full?: string;
    sprite?: string;
    group?: string;
    x?: number;
    y?: number;
    w?: number;
    h?: number;
}
