export interface SkinInterface {

    uuid?: string; //uuid generated by afklol

    // Riot fields
    id: string;
    num: number;
    name: string;
    chromas: boolean;

    // Afklol fields
    videoYtId?:string;
    priceRP?:number;
    dateParution?:string;
}
